#! /bin/sh

sxhkd &

bspc monitor -d '' ''

bspc config pointer_modifier     mod1

bspc config normal_border_color  '#006400'
bspc config focused_border_color '#8B0000'

bspc config window_gap 6
bspc config border_width 3

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled
bspc rule -a Peek state=floating
