#! /bin/sh

pacwall -ug

source ~/.cache/wal/colors.sh

setxkbmap -option caps:escape
setxkbmap -option compose:lwin

pidof unclutter || unclutter -b
pidof redshift  || redshift -t 6500:3500 &
pidof sxhkd     || sxhkd &

bspc config pointer_modifier     mod1

bspc config normal_border_color  "$foreground"
bspc config focused_border_color "$color6"
bspc config presel_feedback_color "$color6"

bspc config window_gap 8
bspc config border_width 4

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled
