#! /bin/sh

sxhkd &

bspc monitor -d '' ''

bspc config pointer_modifier     mod1

bspc config normal_border_color  '#000000'
bspc config focused_border_color '#008b8b'

bspc config window_gap 8
bspc config border_width 4

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled
bspc rule -a Peek state=floating
